import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from 'react-responsive-carousel';
import Link from 'next/link';

const history = () => {
  return (
    <div id="history">
      <div className={styles.container}>
      <Head>
        <title>ORMAS, Koraput</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Kolab_Logo.jpg" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossOrigin="anonymous"></link>
        
      </Head>

      <div className={styles.banner}>

        <div className='mt-4'>
          <div id={styles.welcome}>
            <h3 className={styles.title}>
              Welcome to <a href=" " target="_blank">ORMAS</a> <p className='ml-2 mt-0'>Koraput</p>
              <p className='mt-0 text-2xl text-white italic' >
                Odisha Rural Developement and Marketing Society
              </p>
            </h3>
          </div>

          <div className={styles.grid} >
            <a href="https://twitter.com/abdaal?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" className={styles.card} target="blank" id={styles.cm}>
              <div className='text'>
                <h2 className='font-semibold'>Shri Abdaal M. Akhtar, IAS &rarr;</h2>
                <p>Collector & District Magistrate</p>
              </div>
              <div className={styles.profile}>
                <Image src="/collector.jpg" width="100px" height="100px" className={styles.pic} alt="profile photos"/>   {/*alt */}
              </div>
            </a>

            <a href="" className={styles.card} target="blank">
              <div>
                <h2 className='font-semibold'>Shri Rajendra Majhi, OAS&rarr;</h2>
                <p>CDO-CUM-E.O, Zilla Parisad Koraput.</p>
              </div>
              <div className={styles.profile}>
                <Image src="/" width="100px" height="100px" className={styles.pic} alt="profile photos"/>   {/*alt */}
              </div>
            </a>

            <a href="" className={styles.card} target="blank">
              <div >
                <h2 className='font-semibold'>Shri Roshan Kumar Karthik, &rarr;</h2>
                <p>Deputy CEO, ORMAS Koraput.</p>
              </div>
              <div className={styles.profile}>
                <Image src="/Roshan.jpg" width="100px" height="100px" className={styles.pic} alt="profile photos"/>   {/*alt */}
              </div>
            </a>



          </div>



        </div>
        

        <div className={styles.slider}>
          <div id="carouselExampleIndicators" className="carousel slide" data-ride="carousel">
            <ol className="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" className="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div className="carousel-inner">
              <div className="carousel-item active">
                <Image id={styles.slider_image} className="d-block w-100" src="Workers1.jpeg" alt="First slide" />
              </div>
              <div className="carousel-item">
                <Image id={styles.slider_image} className="d-block w-100" src="Workers2.jpeg" alt="Second slide" />
              </div>
              <div className="carousel-item">
                <Image id={styles.slider_image} className="d-block w-100" src="Workers3.jpeg" alt="Third slide" />
              </div>
              <div className="carousel-item">
                <Image id={styles.slider_image} className="d-block w-100" src="Workers4.jpeg" alt="Third slide" />
              </div>
              <div className="carousel-item">
                <Image id={styles.slider_image} className="d-block w-100" src="Workers5.jpeg" alt="Third slide" />
              </div>
              <div className="carousel-item">
                <Image id={styles.slider_image} className="d-block w-100" src="Workers6.jpeg" alt="Third slide" />
              </div>
              
            </div>
            <a className="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span className="carousel-control-prev-icon" aria-hidden="true"></span>
              <span className="sr-only">Previous</span>
            </a>
            <a className="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span className="carousel-control-next-icon" aria-hidden="true"></span>
              <span className="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>

      <h2 className='flex flex-row justify-center mt-24 font-serif text-2xl font-semibold text-black '>Our Store Location</h2>
      <div className='flex flex-row justify-center mt-10 ' id="second">
        <iframe className='rounded-lg' src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15108.555810503763!2d82.7193501!3d18.7919599!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xe41a46200b702ecf!2sKoraput%20Junction!5e0!3m2!1sen!2sin!4v1660069891134!5m2!1sen!2sin" width="1500" height="450" id={styles.Home_map} />


      </div>

      <main className={styles.main}>

      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="Rohan"
        >
          Powered by {''}
          <h3>
            Rohan
          </h3>
        </a>
      </footer>
      {/*<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossOrigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossOrigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossOrigin="anonymous"></script>*/}
    </div>
    <div className={styles.menu}>
      <h2>Our Journey</h2>
    </div>

    <div id='Our Journey'>
    <section className="text-white bg-black body-font my-10" >
    <div className="container px-5 py-24 mx-auto flex flex-wrap ">
      <h2 className="sm:text-3xl text-2xl text-orange-200 font-medium title-font mb-2 md:w-2/5">Background</h2>
      <div className="md:w-3/5 md:pl-6">
        <p className="leading-relaxed text-base">To create different marketing channels for the micro enterprises, rural producers to develop sustainable livelihood through adopting appropriate rural technology, product development & diversification with accepted designs, packaging, certification, branding activities etc, Government in Panchayati Raj & Drinking Water Department has created “Odisha Rural Development and Marketing Society (ORMAS)” on 14th January 1991and registered under Societies Registration Act-1860, it has been rendering yeomen services in livelihood promotion and rural product marketing in Odisha.  ORMAS and DSMSs have been successfully operating since last 25 years for establishment of a strong marketing network for rural produces.</p>
        <div className="flex md:mt-4 mt-6">
          <a className="text-orange-200 inline-flex items-center hover:cursor-pointer ">Learn More
            <svg fill="none" stroke="currentColor" strokeLinecap="round"   strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
    </div>
  </section>
  
    <section className="text-white bg-black body-font my-10" >
    <div className="container px-5 py-24 mx-auto flex flex-wrap ">
      <h2 className="sm:text-3xl text-2xl text-orange-200 font-medium title-font mb-2 md:w-2/5">The Road Ahead</h2>
      <div className="md:w-3/5 md:pl-6">
        <p className="leading-relaxed text-base">With changing scenario on Government’s strategies for development program implementation which is based on sustainability of these program and as a process capacitating /involving the grass root institutions/civil societies and having equity and transparency at all levels, ORMAS is being positioned to be working in partnership and as an apex body for knowledge creation, flow and adaptation for creating economic opportunities.

ORMAS has already imbibed a role of facilitator rather than implementer and work in partnerships with other institutions/agencies for sustainability of the initiatives which it started long back. While there has been change in ORMAS’s role, at the same time the role of all partners are being evolved.  ORMAS keep on working more at a systemic level.</p>
        <div className="flex md:mt-4 mt-6">
          <a className="text-orange-200 inline-flex items-center hover:cursor-pointer">Learn More
            <svg fill="none" stroke="currentColor" strokeLinecap="round"   strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
    </div>
  </section>
  </div>
  </div>
  

  )
}

export default history